apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven-package
spec:
  workspaces:
  - name: output
  steps:
    - name: maven-package
      image: maven
      script: |
        cd  $(workspaces.output.path); mvn package -s settings.xml | tee $(workspaces.output.path)/package
        exit ${PIPESTATUS[0]}