apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-and-deploy
spec:
  serviceAccountName: tekton
  triggers:
  - name: test
    interceptors:
    - cel:
        filter: "header.match('X-Gogs-Event', 'push')"
        overlays:
        - key: extensions.commit
          expression: "body.after.truncate(7)"
    bindings:
    - Ref: build-and-deploy
    template:
      name: build-and-deploy