apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repository
spec:
  workspaces:
  - name: VOLUME
  params:
  - name: RepositoryURL
    type: string
    description: Url of the git repository to clone.
    default: https://github.com/GMH501/redexporter.git
  - name: Commit
    type: string
    description: Code of the commmit.
  steps:
  - name: git-clone
    image: alpine/git:latest
    script: |
      git clone "$(params.RepositoryURL)" $(workspaces.VOLUME.path)/codebase
  - name: print-commit
    image: alpine/git:latest
    script: |
      cd $(workspaces.VOLUME.path)/codebase && git rev-parse HEAD
      echo "$(params.Commit)"