apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: springapp-deploy-run-01
  labels:
    tekton.dev/pipeline: pipeline-ci
spec:
  pipelineRef:
    name: pipeline-ci
  params:
    - name: "RepositoryURL"
      value: "https://github.com/GMH501/redexporter.git"
  workspaces:
  - name: TKN_VOLUME
    persistentVolumeClaim:
      claimName: test-pvc1
